DROP TABLE IF EXISTS song_fingerprint;

CREATE TABLE song_fingerprint (
    song_id INTEGER PRIMARY KEY,
    amt_intro INTEGER, 
    pos_avg_intro REAL, 
    pos_std_intro REAL, 
    amt_verse INTEGER, 
    pos_avg_verse REAL, 
    pos_std_verse REAL, 
    amt_pre_chorus INTEGER, 
    pos_avg_pre_chorus REAL, 
    pos_std_pre_chorus REAL, 
    amt_chorus INTEGER, 
    pos_avg_chorus REAL, 
    pos_std_chorus REAL, 
    amt_post_chorus INTEGER, 
    pos_avg_post_chorus REAL, 
    pos_std_post_chorus REAL, 
    amt_pre_hook INTEGER, 
    pos_avg_pre_hook REAL, 
    pos_std_pre_hook REAL, 
    amt_hook INTEGER, 
    pos_avg_hook REAL, 
    pos_std_hook REAL, 
    amt_post_hook INTEGER, 
    pos_avg_post_hook REAL, 
    pos_std_post_hook REAL, 
    amt_bridge INTEGER, 
    pos_avg_bridge REAL, 
    pos_std_bridge REAL, 
    amt_outro INTEGER, 
    pos_avg_outro REAL, 
    pos_std_outro REAL, 
    amt_instrumental INTEGER, 
    pos_avg_instrumental REAL, 
    pos_std_instrumental REAL, 
    amt_vamp INTEGER, 
    pos_avg_vamp REAL, 
    pos_std_vamp REAL, 
    amt_break INTEGER, 
    pos_avg_break REAL, 
    pos_std_break REAL, 
    amt_solo INTEGER, 
    pos_avg_solo REAL, 
    pos_std_solo REAL,
    FOREIGN KEY (song_id) REFERENCES song(song_id)
);